apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-router
  labels:
    app: {{ .Release.Name }}
    component: router
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
    component: router
